PULL_REQUEST_TEMPLATE.md

@all-contributors add @uniqueg for content, ideas, maintenance, mentoring, projectManagement

chore: add pull request template

---

.all-contributorsrc
.github/ISSUE_TEMPLATE/another-issue.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTORS
PULL_REQUEST_TEMPLATE.md
README.md

> Please include a summary of the change and the relevant issue(s) it resolves,
> if any (otherwise delete that line). Please also include relevant motivation
> and context briefly, especially if there exists no related issue and the
> change is non-trivial. List any dependencies that are required for this
> change. Please use bullet points for the description. For very trivial issues
> that are duly explained by the PR title, a description can be omitted.
- set up repository template for supporting the [All Contributors Specification](https://allcontributors.org/docs/en/specification)
- add `.all-contributorsrc` configuration file
- add title/placeholder in `CONTRIBUTORS` file
- ask contributors in `README.md` and the pull request and issue templates to request the `@all-contributors` …

chore: support for All Contributors

---

.all-contributorsrc

> Please include a summary of the change and the relevant issue(s) it resolves,
> if any (otherwise delete that line). Please also include relevant motivation
> and context briefly, especially if there exists no related issue and the
> change is non-trivial. List any dependencies that are required for this
> change. Please use bullet points for the description. For very trivial issues
> that are duly explained by the PR title, a description can be omitted.
> Please go through the following checklist to ensure that your change is ready
> for review. Please do not forget to double check the list after you have
> modified your PR, e.g., if you have added commits to address reviewer
> comments or to fix failing automated checks. Please check items also if they
> do not apply to your change, …

fix: invalid JSON in All Contributors config

---

.husky/pre-commit
README.md
package-lock.json
package.json

This commit ensures that all the tests have passed and the files have been linted before comitting, ensuring a much smoother development process and less error prone commits.
fix #35
Having all the files auto linted and tested before commit reduces chances of errors in the commit.
-Fixes #35 
project, including, in particular, with regard to any style guidelines
specification][conventional-commits]; in particular, it clearly indicates
that a change is a breaking change
using the PR title as the commit message.
changed behavior
or updated existing ones
functions/classes/methods or updated existing ones
works
acknowledge my contributions by commenting on this PR with a request of
the form `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1,
TYPE_2, ...`, where `TYPE_1` etc. refer to …

chore: pre-commit hook for testing & linting

---

.github/workflows/main.yml
.github/workflows/semantic.yml

> Please include a summary of the change and the relevant issue(s) it resolves,
> if any (otherwise delete that line). Please also include relevant motivation
> and context briefly, especially if there exists no related issue and the
> change is non-trivial. List any dependencies that are required for this
> change. Please use bullet points for the description. For very trivial issues
> that are duly explained by the PR title, a description can be omitted.
-
Fixes #(issue)
> Please go through the following checklist to ensure that your change is ready
> for review. Please do not forget to double check the list after you have
> modified your PR, e.g., if you have added commits to address reviewer
> comments or to fix failing automated checks. Please check items also if they
> do not apply …

chore(semantic): checks for semantic PR title

---

packages/ecc-client-ga4gh-tes/src/components/tes-create-run/definition/createTask.d.ts
packages/ecc-client-ga4gh-tes/src/components/tes-create-run/definition/tesCreateRun.styles.ts
packages/ecc-client-ga4gh-tes/src/components/tes-create-run/definition/tesCreateRun.template.ts
packages/ecc-client-ga4gh-tes/src/components/tes-create-run/definition/tesCreateRun.ts

setup executors fields duplication to allow multiple inputs collection for executors fields
> Please include a summary of the change and the relevant issue(s) it resolves, if any (otherwise delete that line).
Fixes #(issue)
> Please go through the following checklist to ensure that your change is ready for review.
> If there are unchecked boxes in the list above, but you would still like your PR to be reviewed or considered for merging, please describe here why boxes were not checked.

feat(tes-create-run): setup executors fields duplication

---

packages/ecc-client-ga4gh-trs/package.json

Fixed the fast-components binding issue
> Please go through the following checklist to ensure that your change is ready for review.

Binding bug fix

---

PULL_REQUEST_TEMPLATE.md

> Please include a summary of the change and the relevant issue(s) it resolves, if any (otherwise delete that line).
Fixes #(issue)
> Please go through the following checklist to ensure that your change is ready for review.
> If there are unchecked boxes in the list above, but you would still like your PR to be reviewed or considered for merging, please describe here why boxes were not checked.

fix(pr_template): convert notes to comments

---

package-lock.json
packages/ecc-utils-design/.gitignore
packages/ecc-utils-design/index.html
packages/ecc-utils-design/package.json
packages/ecc-utils-design/rollup.config.js
packages/ecc-utils-design/src/components/button/button.styles.ts
packages/ecc-utils-design/src/components/button/button.template.ts

feat(ecc-utils-design): shoelace integration (#108)

---

packages/ecc-utils-design/index.html
packages/ecc-utils-design/src/components/button/button.ts
packages/ecc-utils-design/src/components/wrapper/wrapper.ts
packages/ecc-utils-design/src/design-system/index.ts
packages/ecc-utils-design/src/design-system/tokens.ts

fix(ecc-utils-design): minor fixes

---

packages/ecc-utils-design/index.html
packages/ecc-utils-design/src/components/button/button.definition.ts
packages/ecc-utils-design/src/components/button/button.styles.ts
packages/ecc-utils-design/src/components/button/button.ts
packages/ecc-utils-design/src/components/wrapper/wrapper.template.ts
packages/ecc-utils-design/src/components/wrapper/wrapper.ts
packages/ecc-utils-design/src/design-system/index.ts
packages/ecc-utils-design/src/design-system/tokens.ts
packages/ecc-utils-design/test/button.test.ts
packages/ecc-utils-design/test/wrapper.test.ts
packages/ecc-utils-design/web-test-runner.config.mjs

added extensive token registeration for tokens passed by user, inlcuding token registeration specific to certain component id. And added testing to verify proper registeration at the wrapper end.
Fixes #101 

feat(ecc-uitls-design): added token registration

---

packages/ecc-client-ga4gh-tes/.eslintrc
packages/ecc-client-ga4gh-tes/README.md
packages/ecc-client-ga4gh-tes/index.html
packages/ecc-client-ga4gh-tes/src/components/index.ts
packages/ecc-client-ga4gh-tes/src/components/tes-create-run/README.md
packages/ecc-client-ga4gh-tes/src/components/tes-run/README.md
packages/ecc-client-ga4gh-tes/src/components/tes-run/definition/tesRun.styles.ts
packages/ecc-client-ga4gh-tes/src/components/tes-run/definition/tesRun.template.ts
packages/ecc-client-ga4gh-tes/src/components/tes-run/definition/tesRun.ts
packages/ecc-client-ga4gh-tes/src/components/tes-runs/README.md
packages/ecc-client-ga4gh-tes/src/components/tes-runs/definition/tesRuns.template.ts
packages/ecc-client-ga4gh-tes/src/components/tes-runs/definition/tesRuns.ts
packages/ecc-client-ga4gh-tes/src/components/tes-service/README.md
packages/ecc-client-ga4gh-tes/src/components/tes-service/definition/tesService.styles.ts
packages/ecc-client-ga4gh-tes/src/components/tes-service/definition/tesService.template.ts
packages/ecc-client-ga4gh-tes/src/components/tes-service/definition/tesService.ts
packages/ecc-client-ga4gh-tes/src/components/tes-service/index.ts
packages/ecc-client-ga4gh-tes/src/data/Task/README.md
packages/ecc-client-ga4gh-tes/src/data/Task/tesGet.ts
packages/ecc-utils-design/index.html
packages/ecc-utils-design/src/components/button/button.styles.ts
packages/ecc-utils-design/src/components/button/button.ts
packages/ecc-utils-design/src/components/wrapper/wrapper.template.ts
packages/ecc-utils-design/src/components/wrapper/wrapper.ts
packages/ecc-utils-design/src/design-system/index.ts
packages/ecc-utils-design/src/design-system/tokens.ts
packages/ecc-utils-design/test/button.test.ts
packages/ecc-utils-design/test/wrapper.test.ts
packages/ecc-utils-design/web-test-runner.config.mjs

merge from main

---

.github/ISSUE_TEMPLATE/general-purpose.md
README.md

docs: update documentation

---

packages/ecc-client-ga4gh-tes/package.json
packages/ecc-client-ga4gh-tes/src/components/tes-create-run/index.ts
packages/ecc-client-ga4gh-tes/src/components/tes-run/index.ts
packages/ecc-client-ga4gh-tes/src/components/tes-runs/index.ts
packages/ecc-client-ga4gh-tes/src/components/tes-service/index.ts
packages/ecc-client-ga4gh-tes/src/index.ts

fix(tes): fix tes component

---

apps/documentation/docs/design/components/collection.md
packages/ecc-utils-design/src/components/collection/collection.ts

feat: pageSize as prop

---

apps/documentation/docs/.vitepress/config.mts
apps/documentation/docs/design/components/form.md
apps/documentation/docs/design/utilities.md
package-lock.json
packages/ecc-utils-design/demo/form/index.html
packages/ecc-utils-design/package.json
packages/ecc-utils-design/scripts/build.js
packages/ecc-utils-design/src/components/form/form.ts
packages/ecc-utils-design/src/components/index.ts
packages/ecc-utils-design/src/index.ts
packages/ecc-utils-design/src/utilities/general.ts
packages/ecc-utils-design/src/utilities/index.ts

feat(ecc-utils-design): add a utility function to get all the css parts  of a component as a string

---

apps/documentation/docs/.vitepress/config.mts
apps/documentation/docs/design/components/form.md
apps/documentation/docs/design/utilities.md
package-lock.json
packages/ecc-utils-design/demo/form/index.html
packages/ecc-utils-design/package.json
packages/ecc-utils-design/scripts/build.js
packages/ecc-utils-design/src/components/form/form.ts
packages/ecc-utils-design/src/components/index.ts
packages/ecc-utils-design/src/index.ts
packages/ecc-utils-design/src/utilities/general.ts
packages/ecc-utils-design/src/utilities/index.ts

feat(ecc-utils-design): add a untility function to get all the css parts of a component as a string

---

packages/ecc-client-lit-ga4gh-tes/demo/index.html
packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/create-run.ts
packages/ecc-utils-design/src/components/form/form.ts

Refactor TES component to improve usability and navigation by implementing collapsible fields in the form.

feat: add collapsible fields

---

apps/documentation/docs/design/components/details.md
packages/ecc-utils-design/demo/details/index.html
packages/ecc-utils-design/src/components/details/details.ts
packages/ecc-utils-design/src/components/index.ts

This pull request introduces an abstraction to the details package. Rather than parsing data at the `package-author` level, the design package now has the capability to parse and render data by inferring its type and other relevant information. The `app-author` will provide the component with `data` to be rendered, which can be in the form of `JSON` or an `Object`. Additionally, other configuration options, such as `fields`, can be passed, defining the spatial and structural configuration for rendering. Lastly, this PR enhances the method for passing button `icons` by utilizing a `slot` with the specified `key` in the button prop.
```html
<ecc-utils-design-details
.data=${data /* JSON or Object */}
.fields=${fields /* Array<Field> */}
.buttons=${buttons /* Array<FooterButton> */}
>
<span …
```

feat(details): add data parsing abstraction 

---

packages/ecc-client-lit-ga4gh-wes/package.json

fix component prefix name that was causing the react component directories to be generated with the wrong name
Fixes #(issue)
#268 

fix(ecc-client-lit-ga4gh-wes): fix component prefix name in package json

---

packages/ecc-client-lit-ga4gh-tes/src/components/create-run/create-run.ts
packages/ecc-client-lit-ga4gh-tes/src/components/runs/runs.ts
packages/ecc-client-lit-ga4gh-wes/src/components/create-run/create-run.ts
packages/ecc-client-lit-ga4gh-wes/src/components/runs/runs.ts
packages/ecc-utils-design/package.json

fixes issue with importing the design package components.

fix(ecc-utils-design): import error

---

.github/workflows/publish.yml

fix: publish script

---

.changeset/perfect-rockets-guess.md
.eslintrc
README.md
package-lock.json
package.json
packages/ecc-client-elixir-trs-filer/.eslintrc
packages/ecc-client-elixir-trs-filer/package.json
packages/ecc-client-ga4gh-tes/.eslintrc
packages/ecc-client-ga4gh-tes/package.json
packages/ecc-client-ga4gh-trs/.eslintrc
packages/ecc-client-ga4gh-trs/package.json
packages/ecc-client-ga4gh-wes/.eslintrc
packages/ecc-client-ga4gh-wes/package.json
packages/ecc-utils-design/.eslintrc
packages/ecc-utils-design/package.json
packages/eslint-config-elixir/CHANGELOG.md
packages/eslint-config-elixir/package.json
turbo/generators/template-package/.eslintrc.hbs
turbo/generators/template-package/package.json.hbs

chore(elixir-cloud-eslint): change scope to @elixir-cloud

---

scripts/build.js

This fixes the issue that causes the build to fail when a file change is made in dev mode
Fixes #310 

fix: build breaking on file change

---

Dockerfile
apps/documentation/nginx.conf

Changes to make nginx rootless
